version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/ApplicationStart
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh
